version: "3"

services:
  api:
    container_name: hestia
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    tty: true
    ports:
      - "3000:3000"
    volumes:
      - type: bind
        source: ./
        target: /hestia
    env_file:
      - .env
